import { api, API_BASE, USE_MOCK, mockDelay, uid } from './api'
import * as reg from '@/mocks/register'
import * as look from '@/mocks/lookups'
import { ampExpiryRag } from '@/utils/rag'
import { loadState, saveState } from '@/utils/persist'
import type { QrCode, ReadonlySiteData, SiteDocument, AcmEntry } from '@/types'

// One token per site (mock store), persisted so the QR-preview tab (opened via
// window.open) can resolve tokens generated in the admin tab.
const TOKENS_KEY = 'asb_qr_tokens_v1'
const tokens: Record<string, string> = loadState(TOKENS_KEY, { 'as-man': 's1' })

// The QR code is auto-generated by the backend when the site is created.
// This is a read-only GET — it returns the existing token, presigned image URL
// and public preview URL. No client-side generation needed.
export async function getQrCode(asbestosSiteId: string): Promise<QrCode> {
  if (USE_MOCK) {
    const token = tokens[asbestosSiteId] ?? (tokens[asbestosSiteId] = uid('tok'))
    saveState(TOKENS_KEY, tokens)
    const previewUrl = `${window.location.origin}/site/${token}/asbestos`
    return mockDelay({ token, qrImageUrl: '', previewUrl, generatedAt: new Date().toISOString(), generatedBy: 'user-sarah' })
  }
  const { data } = await api.get(`${API_BASE}/register/${asbestosSiteId}/qr-code`)
  return {
    token: data.token,
    qrImageUrl: data.qrImageUrl,
    previewUrl: data.previewUrl,
    generatedAt: data.generatedAt,
    generatedBy: data.generatedBy,
  }
}

// Build read-only site data for a given asbestosSiteId. QR page passes
// includeRemediated=false (active only); portals pass true (active + remediated).
function buildReadonly(asbestosSiteId: string, includeRemediated: boolean): ReadonlySiteData {
  const site = reg.sites.find((s) => s.asbestosSiteId === asbestosSiteId)
  if (!site) throw new Error('Invalid or expired link')
  const acmEntries = reg.acmEntries
    .filter((e) => e.asbestosSiteId === asbestosSiteId && (includeRemediated || e.status === 'ACTIVE'))
    .map((e) => ({
      ...e,
      assetName: e.assetId ? (look.assetExists(site.siteId, e.assetId) ? look.assetName(site.siteId, e.assetId) : look.lastKnownAssetName(e.assetId)) : null,
      assetDiscrepancy: !look.assetExists(site.siteId, e.assetId),
    }))
  const documents = reg.documents
    .filter((d) => d.asbestosSiteId === asbestosSiteId && (d.docType !== 'AMP' || d.isCurrentAmp)) // no superseded AMPs
    .map((d) => ({ ...d, ampExpiryRag: d.docType === 'AMP' ? ampExpiryRag(d.ampExpiryDate) : null }))
  return { siteName: look.siteName(site.siteId), customerName: look.customerName(site.customerId), acmEntries, documents }
}

// Public, login-free QR page data (active entries only) resolved by token.
// The backend serves this at the root /public/{token} (NOT under the asbestos
// API base) and returns its own JSON shape: documents carry a presigned `url`
// (no id / uploadedAt / isCurrentAmp), ACM entries use the admin field names
// (`building`, `acmType`). We map both into the ReadonlySiteData the shared
// read-only views expect, synthesising the fields the public payload omits.
export async function getPublicSite(token: string): Promise<ReadonlySiteData> {
  if (USE_MOCK) {
    const asbestosSiteId = Object.keys(tokens).find((k) => tokens[k] === token)
    if (!asbestosSiteId) throw new Error('Invalid or expired link')
    return mockDelay(buildReadonly(asbestosSiteId, false))
  }
  const { data } = await api.get(`/public/${token}`)
  if (data?.success === false) throw new Error(data.message ?? 'Invalid or expired link')
  /* eslint-disable @typescript-eslint/no-explicit-any */
  const documents = (data.documents ?? []).map((d: any, i: number): SiteDocument => ({
    id: d.id ?? `pub-doc-${i}`,
    asbestosSiteId: '',
    docType: d.docType,
    fileName: d.fileName,
    // Public payload exposes the presigned link as `url`; map it to downloadUrl
    // so the shared view/download handlers (which read downloadUrl) work.
    downloadUrl: d.url ?? d.downloadUrl ?? null,
    fileUrl: d.url ?? d.fileUrl ?? null,
    ampExpiryDate: d.ampExpiryDate ?? null,
    ampExpiryRag: d.ampExpiryRag ?? (d.docType === 'AMP' ? ampExpiryRag(d.ampExpiryDate) : null),
    isCurrentAmp: d.docType === 'AMP', // public API only returns the current AMP
    uploadedAt: d.uploadedAt ?? '',
    uploadedById: d.uploadedBy ?? '',
    uploadedByName: d.uploadedByName ?? '',
  }))
  const acmEntries = (data.acmEntries ?? []).map((e: any): AcmEntry => ({
    id: e.id,
    asbestosSiteId: e.asbestosSiteId ?? '',
    buildingTypeId: e.buildingTypeId ?? '',
    buildingTypeName: e.building ?? e.buildingTypeName ?? '',
    roomLocation: e.roomLocation,
    assetId: e.assetId ?? null,
    assetName: e.assetName ?? null,
    assetDiscrepancy: false,
    acmTypeId: e.acmTypeId ?? '',
    acmTypeName: e.acmType ?? e.acmTypeName ?? '',
    condition: e.condition,
    riskScore: e.riskScore,
    notes: e.notes ?? null,
    status: e.status,
    attachments: (e.attachments ?? []).map((a: any) => ({
      id: a.id,
      fileName: a.fileName,
      downloadUrl: a.url ?? a.downloadUrl ?? null,
      fileUrl: a.url ?? a.fileUrl ?? null,
    })),
  }))
  /* eslint-enable @typescript-eslint/no-explicit-any */
  return {
    siteName: data.siteName ?? '',
    customerName: data.customerName ?? '',
    acmEntries,
    documents,
  }
}

// View-Only portal data (active + remediated) by asbestosSiteId.
export async function getPortalSite(asbestosSiteId: string): Promise<ReadonlySiteData> {
  if (USE_MOCK) return mockDelay(buildReadonly(asbestosSiteId, true))
  const { data } = await api.get(`${API_BASE}/register/${asbestosSiteId}`)
  /* eslint-disable-next-line @typescript-eslint/no-explicit-any */
  return {
    siteName: data.site?.siteName ?? '',
    customerName: data.site?.customerName ?? '',
    acmEntries: (data.acmEntries ?? []).map((e: any) => ({
      id: e.id, asbestosSiteId: e.asbestosSiteId,
      buildingTypeId: e.buildingTypeId, buildingTypeName: e.buildingTypeName,
      roomLocation: e.roomLocation, assetId: e.assetId, assetName: e.assetName,
      assetDiscrepancy: e.assetDiscrepancy ?? false,
      acmTypeId: e.acmTypeId, acmTypeName: e.acmTypeName,
      condition: e.condition, riskScore: e.riskScore, notes: e.notes,
      status: e.status, attachments: e.attachments ?? [],
      updatedAt: e.updatedAt, updatedById: e.updatedBy, updatedByName: e.updatedByName,
    })),
    documents: (data.documents ?? []).filter((d: any) => d.docType !== 'AMP' || d.isCurrentAmp),
  }
}

export { ampExpiryRag }
